article/urls.py
# 引入path
from django.urls import path
from . import views

# 正在部署的应用的名称
app_name = 'article'

#url路由配置
urlpatterns = [
    #所有文章列表
    path('article_list/',views.article_list,name="article_list"),
    #文章详情
    path('article_detail/<int:id>/',views.article_detail,name='article_detail'),
    #写文章
    path('article_create/',views.article_create,name='article_create'),
    #删除文章(不安全的删除)
    #path('article_delete/<int:id>/',views.article_delete,name='article_delete'),
    #安全删除文章
    path('article_safe_delete/<int:id>/',views.article_safe_delete,name='article_safe_delete'),
    #修改文章
    path('article_update/<int:id>/',views.article_update,name='article_update'),
    #新建栏目
    path('column_create',views.column_create,name="column_create"),
    #点赞
    path('clicklike/<int:article_id>',views.clicklike,name='clicklike'),
    #推荐
    path('Recommendation/',views.Recommendation,name='Recommendation')
]

my_blog/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
import notifications.urls
from article.views import article_list

#用于存放映射关系的列表
urlpatterns = [
    #首页
    path('', article_list, name='home'),
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('accounts/', include('allauth.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表  类视图的调用
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    #用户注册
    path('register/',views.user_register,name='register'),
    #退出登录
    path('logout/',views.user_logout,name='logout'),
    #注销账号
    path('delete/<int:id>/',views.user_delete,name='delete'),
    #用户信息
    path('edit/<int:id>/',views.profile_edit,name='edit'),
    #用户主页
    path('personal/<int:id>',views.user_personal,name='personal'),
    #点击关注按钮
    path('focus/<int:id>',views.clickfocus,name='focus'),
]

userprofile/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

from article.models import likes
#用户扩展信息
from django.db.models.signals import post_save
from django.dispatch import receiver

#关注关系表
class userfocus(models.Model):
    #博主
    blogger = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blogger')
    #粉丝
    fans = models.ForeignKey(User,on_delete=models.CASCADE,related_name='fans')


class Profile(models.Model):
    #与User模型构成一对一的关系
    #关联外键   每个profile模型对应一个user模型,可以添加各种扩展信息,而不用对user表进行改动
    #on_delete参数当该表中的某条数据删除后，关联外键的操作
    #   models.CASCADE表示级联删除,删除一个表的某条数据后对应表的数据也删除
    #   models.SET_NULL表示,删除一个表的某条数据后另一个表的对应数据置空,字段要允许为空
    #   models.SET_DEFAULT,删除后置为默认值
    #   PROTECT 阻止前面的删除操作，报出ProtectedError异常
    #   DO_NOTHING 什么也不做
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='profile')

    #电话号码
    phone = models.CharField(max_length=20,blank=True)
    #头像 图像字段需要第三方库pillow支持
    #ImageField字段不会存储图片本身，而仅仅保存图片的地址
    avatar = models.ImageField(upload_to="avatar/%Y%m%d/",blank=True)
    #个人简介
    bio = models.TextField(max_length=500,blank=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)

#信号接收函数,每当新建User实例时自动调用
#django包含信号调度程序,在框架中某些位置发生某种操作时,通知其他应用程序
#post_save是一个内置信号,在模型调用save方法后发出信号(信号中还带有相关的数据)
#装饰器receiver用于接收信号,这里表示接收User模型调用save方法时发出的信号
#接收到信号后执行后面的函数
@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)

#两个函数都接收来自User的save信号
#根据函数的参数created来判断是创建用户还是修改用户信息
#post_save = ModelSignal(providing_args=["instance", "raw", "created", "using", "update_fields"],
#created不为空即为创建用户
#所有save情况都执行修改操作
@receiver(post_save,sender=User)
def save_user_profile(sender,instance,**kwargs):
    instance.profile.save()

userprofile/forms.py
#引入表单类
from django import forms
#引入User模型
from django.contrib.auth.models import User

#用户登录表单,继承了forms.Form类 适用于不于数据库进行直接交互的功能
#而文章表单继承的forms.ModelForm适用于需要直接与数据库交互的功能
from .models import Profile


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

#用户注册表单类
class UserRegisterForm(forms.ModelForm):
    #输入两次密码
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username','email')

    #对两次输入的密码检查是否一致 clean_**方法django会自动调用
    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError('密码输入不一致，请重新输入')

#用户扩展信息表单类
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone','avatar','bio')

userprofile/views.py
from article.models import ArticlePost
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from .forms import UserLoginForm, UserRegisterForm
from .models import Profile, likes, userfocus
from .forms import ProfileForm

#关注按钮点击
def clickfocus(request,id):
    #根据当前用户id和id查询关注信息表
    focusrecoder = userfocus.objects.filter(Q(blogger_id=id) | Q(fans_id=request.user.id))
    if focusrecoder:
        focusrecoder.delete()
    else:
        newfocus = userfocus(blogger=User.objects.get(id=id),fans=request.user)
        newfocus.save()
    return redirect("userprofile:personal",id)


#用户主页信息
def user_personal(request,id):
    #用户对象实例
    user = User.objects.get(id=id)
    #用户扩展信息实例
    profile = Profile.objects.get(user_id=id)
    #用户写的文章列表
    articles = ArticlePost.objects.filter(author_id=id)
    articlenum = articles.count()
    #点赞数
    likenum = 0
    for article in articles:
        likelist = likes.objects.filter(article_id=article.id)
        likenum += likelist.count()
    #关注数
    focuslist = userfocus.objects.filter(fans_id=id)
    focusnum = focuslist.count()
    #粉丝数
    fanslist = userfocus.objects.filter(blogger_id=id)
    fansnum = fanslist.count()
    #是否已经关注
    focusrecoder = userfocus.objects.filter(Q(blogger_id=id) | Q(fans_id=request.user.id))
    if focusrecoder:
        isfocus = True
    else:
        isfocus = False

    #上下文
    context = {'blogger':user,'profile':profile,'likenum':likenum,'focusnum':focusnum,'fansnum':fansnum,'articlenum':articlenum,'articles':articles,'isfocus':isfocus}
    return render(request,'userprofile/personal.html',context)

def user_login(request):
    #post请求提交表单
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        #如果数据符合表单模型要求
        if user_login_form.is_valid():
            #.cleaned_data,清洗出合法数据
            print(user_login_form)
            data = user_login_form.cleaned_data
            #检验账号密码是否正确匹配数据库的某个用户
            #如果均匹配成功则返回这个user对象
            user = authenticate(username=data['username'], password=data['password'])
            #如果匹配成功则user不为空
            if user:
                #将用户数据保存在session中,就实现了登录操作
                login(request,user)
                return redirect("article:article_list")
            else:
                return HttpResponse("账号或密码输入有误,请重新输入~")
        else:
            return HttpResponse("账号或密码输入不合法")
    #get请求获取表单
    elif request.method == 'GET':
        #创建表单对象
        user_login_form = UserLoginForm()
        #用于返回的变量
        context = {'form':  user_login_form}
        #返回页面和变量
        return render(request,'userprofile/login.html',context)
    #既不是post也不是get请求
    else:
        return HttpResponse("请使用GET或POST请求数据")

#用户注册
def user_register(request):
    #post请求提交表单
    if request.method == 'POST':
        #创建用户注册表单实例并赋值
        user_register_form = UserRegisterForm(data = request.POST)
        if user_register_form.is_valid():
            #保存用户注册表单实例，暂时不提交到数据库
            new_user = user_register_form.save(commit=False)
            #设置密码
            new_user.set_password(user_register_form.cleaned_data['password'])
            #设置密码后的表单对象存入数据库
            new_user.save()
            #保存好数据库后立刻登录并返回博客列表页面
            login(request,new_user)
            return redirect("article:article_list")
        else:
            return HttpResponse("注册表单输入有误，请重新输入。")
    elif request.method == 'GET':
        #创建空注册表单实例
        user_register_form = UserRegisterForm()
        #返回的数据
        context = {'form' : user_register_form}

        return render(request,'userprofile/register.html',context)
    else:
        return HttpResponse("请使用GET或POST请求")

#用户退出
def user_logout(request):
    #使用logout类中的方法退出登录
    logout(request)
    #返回文章列表页面
    return redirect("article:article_list")

#用户注销账号
#python装饰器
#要掉用delete函数必须要登录,没有登录则重定向到登录页面
@login_required(login_url='/userprofile/login/')
def user_delete(request,id):
    #判断请求方式
    if request.method == "POST":
        #根据id获取需要操作的对象
        user = User.objects.get(id=id)
        #验证登录用户，和需要执行删除操作的用户是否相同
        if request.user == user:
            #退出登录
            logout(request)
            #删除用户数据
            user.delete()
            #返回博客列表
            return redirect("article:article_list")
        else:
            return HttpResponse("你没有删除操作权限")
    else:
        return HttpResponse("仅接受post请求")

#编辑用户信息
@login_required(login_url='/userprofile/login/')
def profile_edit(request,id):
    #根据id获取需要修改的用户对象
    user = User.objects.get(id=id)
    #user_id是OneToOneField自动生成的字段
    #根据此字段获取user对应的信息
    profile = Profile.objects.get(user_id=id)

    if request.method == 'POST':
        #验证修改数据的用户是不是被修改的用户
        if request.user != user:
            return HttpResponse("你没有权限修改此用户信息")
        # 上传的文件保存在 request.FILES 中，通过参数传递给表单类
        profile_form = ProfileForm(request.POST,request.FILES)
        #如果数据合法
        if profile_form.is_valid():
            #得到清洗数据
            profile_cd = profile_form.cleaned_data
            #获取各属性值
            profile.phone = profile_cd['phone']
            profile.bio = profile_cd['bio']
            # 如果 request.FILES 存在键为avatar的数据，则获取该数据
            if 'avatar' in request.FILES:
                profile.avatar = profile_cd["avatar"]
            profile.save()
            #带参数的redirect
            return redirect("userprofile:edit",id=id)
        else:
            return HttpResponse("表单输入有误，请重新输入~")
    elif request.method == 'GET':
        profile_form = ProfileForm()
        context = {'profile_form':profile_form,'profile':profile,'user':user}
        return render(request,'userprofile/edit.html',context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

templates/userprofile/edit.html
{% extends "base.html" %} {% load static %}
{% block title %} 用户信息 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <div class="col-md-4">用户名: {{ user.username }}</div>
            <br>
            {# 判断用户是否上传头像 #}
            {% if profile.avatar %}
                <div class="col-md-4">头像</div>
                <img src="{{ profile.avatar.url }}" style="max-width: 20%; border-radius: 15%;" class="col-md-4">
            {% else %}
                <h5 class="col-md-4">暂无头像</h5>
            {% endif %}
            <br>
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="avatar">上传头像</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
                <div class="form-group col-md-4">
                    <label for="phone">电话</label>
                    <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                </div>
                <div class="form-group col-md-4">
                    <label for="bio">简介</label>
                    <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/login.html
{# 继承模板和静态文件 #}
{% extends "base.html" %} {% load static %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <h5>还没有账号？</h5>
            <h5>点击<a href='{% url "userprofile:register" %}'>注册账号</a>加入我们吧！</h5>
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group col-md-4">
                    <label for="username">账号</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
                <!-- 密码 -->
                <div class="form-group col-md-4">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
            <br>
            <h5>忘记密码了？</h5>
            <h5>点击<a href='{% url "password_reset_recover" %}'>这里</a>重置密码</h5>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/personal.html
{% extends "base.html" %}
{% load static %}
{% block title %}
博主详情页面
{% endblock %}
{% block content %}
    <div class="container" style="padding-top: 60px">
        <div class="row">
            {# 用户信息 #}
            <div class="col-3">
                {# 用户信息 #}
                {% if profile.avatar %}
                    <div style="height: 200px;width: 200px">
                        <img src="{{ profile.avatar.url }}" alt="" style="max-width: 100%;max-height: 100%">
                    </div>

                {% endif %}
                <div>
                    <h2>{{ blogger.username }}</h2>
                </div>
                <div>
                    {% if isfocus %}
                        <button onclick="clickfocus()" class="btn btn-light">
                            取消关注
                        </button>
                    {% else %}
                        <button onclick="clickfocus()" class="btn btn-light">
                            关注博主
                        </button>
                    {% endif %}
                    {# 一个隐藏的表单 #}
                    <form
                            style="display: none;"
                            id="clickfocus"
                            action="{% url 'userprofile:focus' blogger.id %}"
                            method="post"
                    >
                    {% csrf_token %}
                        <button type="submit">发送</button>
                    </form>
                </div>
                <p>{{ profile.bio }}</p>
                <table class="table">
                    <thead>
                        <tr>
                          <th scope="col">关注</th>
                          <th scope="col">粉丝</th>
                          <th scope="col">文章</th>
                          <th scope="col">获赞</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                          <td>{{ focusnum }}</td>
                          <td>{{ fansnum }}</td>
                          <td>{{ articlenum }}</td>
                          <td>{{likenum}}</td>
                        </tr>
                    </tbody>
                </table>
                <hr>
            </div>
            {# 用户的博客信息 #}
            <div class="col-9">
                {# 遍历articles列表 #}
                {% for article in articles %}
                    {# 文章内容 #}
                    <div class="col-12">
                        {# 栏目 #}
                        {% if article.column %}
                            <button type="button" class="btn btn-sm mb-2 btn-success" onclick='window.location.href="{% url 'article:article_list' %}?column={{ article.column.id }}"'>
                                {{ article.column }}
                            </button>
                        {% endif %}
                        {# 标签 #}
                        <span>
                            {% for tag in article.tags.all %}
                                {# 返回文章列表的链接，带有当前的tag参数 #}
                                <a href="{% url 'article:article_list' %}?tag={{ tag }}"
                                   class="badge badge-secondary"
                                >
                                    {{ tag }}
                                </a>
                            {% endfor %}
                        </span>
                        {# 标题 #}
                        <h4>
                            <b>
                                <a href="{% url 'article:article_detail' article.id %}"
                                   style="color: black;"
                                >
                                    {{ article.title }}
                                </a>
                            </b>
                        </h4>
                        {# 摘要 #}
                        <div>
                            <p style="color: gray;">
                                {{ article.body|slice:'100' }}...
                            </p>
                        </div>
                        {# 注脚 #}
                        <p>
                            <span style="color: green;">
                                <i class="fa fa-eye"></i>
                                {{ article.total_views }} 浏览&nbsp;&nbsp;&nbsp;
                            </span>
                            <span>
                                <i class="fa fa-comments" style="color: yellowgreen;"></i>
                                <!-- 修改为评论的计数 -->
                                {{ article.comments.count }}&nbsp;&nbsp;&nbsp;
                            </span>
                            <span style="color: blue;">
                                {{ article.created|date:'Y-m-d' }} 发布&nbsp;&nbsp;&nbsp;
                            </span>
                            <span style="color: darkred;">

                                {{ article.updated|date:'Y-m-d' }} 更新
                            </span>
                        </p>
                        <hr>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <script>
        function clickfocus() {
            $('form#clickfocus button').click();
        }
    </script>
{% endblock %}

templates/userprofile/register.html
{% extends "base.html" %} {% load static %}
{% block title %} 注册 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group col-md-4">
                    <label for="username">用户名</label>
                    <input type="text" class="form-control" id="username" name="username" required placeholder="请输入用户名">
                </div>
                <!-- 邮箱 -->
                <div class="form-group col-md-4">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email" placeholder="请输入邮箱">
                </div>
                <!-- 密码 -->
                <div class="form-group col-md-4">
                    <label for="password">设置密码</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <!-- 确认密码 -->
                <div class="form-group col-md-4">
                    <label for="password2">确认密码</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/userlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>