my_blog/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
import notifications.urls
from article.views import article_list

#用于存放映射关系的列表
urlpatterns = [
    #首页
    path('', article_list, name='home'),
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('accounts/', include('allauth.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表  类视图的调用
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

notice/models.py
from django.db import models

# Create your models here.

notice/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from article.models import ArticlePost

#通知列表的 类视图  #继承自ListView  用于展示所有的未读通知
#继承了"混入类"LoginRequiredMixin，要求调用此视图必须先登录
class CommentNoticeListView(LoginRequiredMixin,ListView):
    #上下文名称
    context_object_name = 'notices'
    #模板位置
    template_name = 'notice/list.html'
    #登录重定向
    login_url = '/userprofile/login/'

    #未读通知的查询集
    def get_queryset(self):
        #返回了传递给模板的上下文对象
        #unread()方法是django-notifications提供的，用于获取所有未读通知的集合
        return self.request.user.notifications.unread()

#更新通知状态
#继承自View
class CommentNoticeUpdateView(View):
    #处理get请求
    def get(self,request):
        #获取未读通知
        notice_id = request.GET.get('notice_id')
        #更新单条通知
        if notice_id:
            article = ArticlePost.objects.get(id=request.GET.get('article_id'))
            #将未读通知转换为已读
            request.user.notifications.get(id=notice_id).mark_as_read()
            return redirect(article)
        #更新全部通知
        else:
            #将全部未读通知转换为已读
            request.user.notifications.mark_all_as_read()
            return redirect('notice:list')

templates/notice/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
通知
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row mt-4 ml-4">
        <a href="{% url "notice:update" %}" class="btn btn-warning" role="button">清空所有通知</a>
    </div>
    {# 未读通知列表 #}
    <div class="row mt-2 ml-4">
        <ul class="list-group">
            {# 遍历通知列表 #}
            {% for notice in notices %}
                <li class="list-group-item" id="notice_link">
                    {# ?后面的是查询参数  #后面的是锚点 ?不能够传递到下个页面的url中去，而#可以 #}
                    <a href="{% url "notice:update" %}?article_id={{ notice.target.id }}&notice_id={{ notice.id }}#comment_elem_{{ notice.action_object.id }}"
                       target="_blank"
                    >
                    <span style="color: #5897fb;">
                        {{ notice.actor }}
                    </span>
                        在 <span style="color: #01a252;">{{ notice.target }}</span> {{ notice.verb }}。
                    </a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ notice.timestamp|date:"Y/m/d H:i" }}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

<style>
    #notice_link a:link {
        color: black;
    }

    #notice_link a:visited {
        color: lightgrey;
    }
</style>
{% endblock content %}