article/urls.py
# 引入path
from django.urls import path
from . import views

# 正在部署的应用的名称
app_name = 'article'

#url路由配置
urlpatterns = [
    #所有文章列表
    path('article_list/',views.article_list,name="article_list"),
    #文章详情
    path('article_detail/<int:id>/',views.article_detail,name='article_detail'),
    #写文章
    path('article_create/',views.article_create,name='article_create'),
    #删除文章(不安全的删除)
    #path('article_delete/<int:id>/',views.article_delete,name='article_delete'),
    #安全删除文章
    path('article_safe_delete/<int:id>/',views.article_safe_delete,name='article_safe_delete'),
    #修改文章
    path('article_update/<int:id>/',views.article_update,name='article_update'),
    #新建栏目
    path('column_create',views.column_create,name="column_create"),
    #点赞
    path('clicklike/<int:article_id>',views.clicklike,name='clicklike'),
    #推荐
    path('Recommendation/',views.Recommendation,name='Recommendation')
]

my_blog/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
import notifications.urls
from article.views import article_list

#用于存放映射关系的列表
urlpatterns = [
    #首页
    path('', article_list, name='home'),
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('accounts/', include('allauth.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表  类视图的调用
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    #用户注册
    path('register/',views.user_register,name='register'),
    #退出登录
    path('logout/',views.user_logout,name='logout'),
    #注销账号
    path('delete/<int:id>/',views.user_delete,name='delete'),
    #用户信息
    path('edit/<int:id>/',views.profile_edit,name='edit'),
    #用户主页
    path('personal/<int:id>',views.user_personal,name='personal'),
    #点击关注按钮
    path('focus/<int:id>',views.clickfocus,name='focus'),
]

templates/back_to_top.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/back_to_top_func.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
<!-- 载入静态文件 -->
{# 模板中加上这句后,才能使用{% static 'path' %}引入静态文件 #}
{% load static %}

<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">

    {#  网页标题预留block title  #}
    <title>{% block title %}{% endblock %}</title>

    {#  引入bootstrap的css文件,不使用绝对路径,修改static目录后只需要修改static配置路径  #}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/perldoc.css' %}">
    {# 引入网页图标 #}
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    {# 引入fontawesome #}
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'mystyle/header.css' %}">
    <link rel="stylesheet" href="{% static 'mystyle/footer.css' %}">
    {% block style %}{% endblock %}
</head>
<body>
{#引入导航栏#}
{% include 'header.html' %}
{#页面主体预留位置#}
<div id="wrapper">
    {% block content %}{% endblock content %}
    <div id="push"></div>
</div>
{# 引入注脚 #}
{% include 'footer.html' %}

<!--bootstrap.js依赖jquery.js和pooper.js,先引入这两个文件-->
<script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'popper/popper-1.14.4.js' %}"></script>
<!--再引入bootstrap.js文件-->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- 引入layer.js -->
<script src="{% static 'layer/layer.js' %}"></script>
{% block script %}{% endblock script %}
{% include 'back_to_top.html' %}
<style>
    html, body {
        height: 100%;
        margin: 0;
    }

    #wrapper {
        min-height: 100%;
        margin-bottom: -60px;
    }

    #footer,
    #push {
        height: 60px;
    }
</style>
</body>
</html>

templates/footer.html
{% load static %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-secondary" id="footer">
    <div class="container">
        <p class="m-0 text-center text-white" style="color: #808080">Copyright &copy; xiaowei2020</p>
    </div>
</footer>

templates/header.html
{# 引入notifications的模板标签 #}
{% load notifications_tags %}
{% notifications_unread as unread_count %}
{# 导航栏 #}
<nav class="navbar navbar-expand-lg  navbar-light bg-light">
  <div class="container">


    {# 导航栏标题 #}
    <a class="navbar-brand" href="#">旺仔小EZ</a>

    {# 导航栏链接 #}
    <div>
      <ul class="navbar-nav">
        {# 文章列表链接 #}
        <li class="nav-item">
            {# 指向文章列表的链接 #}
          <a class="nav-link" href="{% url 'article:article_list' %}">首页</a>
        </li>
        {# if语句判断是否已经登录 #}
        {# .is_authenticated是models.User类的属性,用于判断用户是否已经通过身份验证 #}
        {% if user.is_authenticated %}
            {# 如果用户已经登录，则显示用户名下拉框 #}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {# 红点通知 #}
                    {% if unread_count %}
                        {# svg是绘制矢量图形的标签 #}
                        <svg viewBox="0 0 8 8"
                             width="8px"
                             height="8px">
                            <circle cx="4"
                                    cy="4"
                                    r="4"
                                    fill="#ff6b6b"
                                    ></circle>
                        </svg>
                    {% endif %}
                    {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url "notice:list" %}">消息通知
                        {% if unread_count %}
                        <span class="badge badge-danger">{{ unread_count }}</span>
                        {% endif %}
                    </a>
                    <a class="dropdown-item" href="{% url 'article:article_create' %}">写博客</a>
                    <a class="dropdown-item" href='{% url "userprofile:personal" user.id %}'>个人主页</a>
                    <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>修改个人信息</a>
                    <a class="dropdown-item" href="#" onclick="user_delete()">注销账号</a>
                    <a class="dropdown-item" href="{% url "userprofile:logout" %}">退出登录</a>
                </div>
            </li>
        {# 如果用户未登录，则显示"登录" #}
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">登录</a>
            </li>
        <!-- if 语句在这里结束 -->
        {% endif %}
        {% if user.is_authenticated %}
        {# 一个隐藏的post请求表单,调用删除用户的视图 #}
        <form
            style="display:none;"
            id="user_delete"
            action="{% url 'userprofile:delete' user.id %}"
            method="POST"
        >
        {% csrf_token %}
            <button type="submit">发送</button>
        </form>
            {# 点击删除后调用的函数, 用于确认删除和执行post请求表单的发送#}
            <script>
                function user_delete() {
                    layer.open({
                        title: "确认删除",
                        content: "确认删除用户资料吗？",
                        yes: function(index, layero) {
                            //点击表单的提交按钮
                            $('form#user_delete button').click();
                            layer.close(index);
                        },
                    })
                }
            </script>
        {% endif %}
      </ul>
    </div>

  </div>
</nav>