article/urls.py
# 引入path
from django.urls import path
from . import views

# 正在部署的应用的名称
app_name = 'article'

#url路由配置
urlpatterns = [
    #所有文章列表
    path('article_list/',views.article_list,name="article_list"),
    #文章详情
    path('article_detail/<int:id>/',views.article_detail,name='article_detail'),
    #写文章
    path('article_create/',views.article_create,name='article_create'),
    #删除文章(不安全的删除)
    #path('article_delete/<int:id>/',views.article_delete,name='article_delete'),
    #安全删除文章
    path('article_safe_delete/<int:id>/',views.article_safe_delete,name='article_safe_delete'),
    #修改文章
    path('article_update/<int:id>/',views.article_update,name='article_update'),
    #新建栏目
    path('column_create',views.column_create,name="column_create"),
    #点赞
    path('clicklike/<int:article_id>',views.clicklike,name='clicklike'),
    #推荐
    path('Recommendation/',views.Recommendation,name='Recommendation')
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 发表评论 由于评论总是依赖于某一篇文章,评论的发表也需要文章的id
    path('post_comment/<int:article_id>/', views.post_comment, name='post_comment'),
    # 处理二级回复
    path('post_comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply'),
    #删除评论
    path('delete_comment/<int:id>/',views.delete_comment,name='delete_comment'),


]

my_blog/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
import notifications.urls
from article.views import article_list

#用于存放映射关系的列表
urlpatterns = [
    #首页
    path('', article_list, name='home'),
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('accounts/', include('allauth.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表  类视图的调用
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    #用户注册
    path('register/',views.user_register,name='register'),
    #退出登录
    path('logout/',views.user_logout,name='logout'),
    #注销账号
    path('delete/<int:id>/',views.user_delete,name='delete'),
    #用户信息
    path('edit/<int:id>/',views.profile_edit,name='edit'),
    #用户主页
    path('personal/<int:id>',views.user_personal,name='personal'),
    #点击关注按钮
    path('focus/<int:id>',views.clickfocus,name='focus'),
]

article/models.py
from django.db import models
# 导入内建的User模型。
from django.contrib.auth.models import User
# timezone 用于处理时间相关事务。
from django.utils import timezone

from django.urls import reverse
#
from PIL import Image
#第三方库app标签
from taggit.managers import TaggableManager

#文章的栏目模型
class ArticleColumn(models.Model):
    #栏目作者 外键 允许为空
    author = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    #栏目标题
    title = models.CharField(max_length=100,blank=True)
    #创建时间
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class ArticlePost(models.Model):
    #文章作者，ForeignKey表示外键 user ，on_delete指定数据删除连带方式
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    #文章标题，字符串类型，最大长度为100
    title = models.CharField(max_length=100)
    #文章正文，大文本使用TextField字段
    body = models.TextField()
    #文章创建时间，default = timezone.now表示默认值为当前时间
    created = models.DateTimeField(default=timezone.now)
    #文章更新时间，每次数据更新自动写入系统当前时间
    updated = models.DateTimeField(auto_now=True)
    #文章浏览量  PositiveIntegerField正整数字段,初值设为0
    total_views = models.PositiveIntegerField(default=0)
    #文章栏目   关联外键栏目 栏目与文章一对多的关系
    column = models.ForeignKey(ArticleColumn,null=True,blank=True,on_delete=models.CASCADE,related_name='article')
    #文章标签
    tags = TaggableManager(blank=True)

    #内部类 class Meta用于给model定义元数据（元信息）
    class Meta:
        #db_table:定义数据表名，推荐使用小写字母，数据表名默认为**项目名_类名
        #ordering:对象的默认排序字段     加负号则代表倒叙
        ordering = ('-created',)

    #函数__str__定义当调用对象的str()方法时的返回值内容
    def __str__(self):
        #返回文章标题
        return self.title

    # 获取文章地址    使用reverse()方法返回文章详情页面的url，实现路由重定向
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

# 点赞关系表
class likes(models.Model):
    #被点赞的文章
    article = models.ForeignKey(ArticlePost,on_delete=models.CASCADE,related_name='article')
    #点赞的用户
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user')

article/forms.py
#form类，描述一张表单并决定如何工作及呈现

#引入表单类
from django import forms
#引入文章模型类
from .models import ArticlePost, ArticleColumn


#写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        #指明数据模型来源
        model = ArticlePost
        #定义表单包含的字段
        fields = ('title','body','tags')

#栏目的表单类
class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('title',)

article/views.py
from comment.models import Comment
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

#引入文章模型类
from article.models import ArticlePost,ArticleColumn,likes
#引入markdown库
import markdown
#引入分页模块
from django.core.paginator import Paginator
#引入django内部的views模块
from django.views import View
#引入评论表单类
from comment.forms import CommentForm

#类视图
class ArticleListView(View):
    """处理get请求"""
    def get(self,request):
        articles = ArticlePost.objects.all()
        context = {'article':articles}
        return render(request,'article/list.html',context)

#文章推荐
@login_required(login_url='account_login')
def Recommendation(request):
    #当前用户
    thisuser = User.objects.get(id=request.user.id)
    #获取用户的点赞文章列表
    likelist = likes.objects.filter(user=request.user.id)
    likearticlelist = []
    for like in likelist:
        likearticlelist.append(like.article)
    #求标签向量平均值
    #标签字典的列表
    tagDictionaries = []
    for article in likearticlelist:
        #每篇文章对应标签字典
        tagDictionary = {}
        #给标签字典赋值
        tags = article.tags.slugs()
        for tag in tags:
            tagDictionary[tag] = 1
        #将字典添加到列表中
        tagDictionaries.append(tagDictionary)
    # print("标签字典的列表：")
    # print(tagDictionaries)
    #求标签平均值
    taglike = {}
    #遍历标签字典列表
    for tagDictionary in tagDictionaries:
        #遍历当前标签字典
        for tag in tagDictionary:
            #如果当前标签在taglike中已存在
            if tag in taglike:
                #值加一
                taglike[tag] += 1
            #不存在则添加新键值对
            else:
                taglike[tag] = 1
    for key in taglike.keys():
        taglike[key] /= len(tagDictionaries)
    #现在用taglike字典的值表示用户对某标签的喜爱程度
    # print("标签平均值：")
    # print(taglike)
    #接下来将博客系统的文章列表按照  算法公式的值  排序
    #所有文章列表
    articlelist = ArticlePost.objects.all()
    #公式计算用户对任一文章的喜爱程度，存在字典中
    #文章id与喜爱度对应的字典
    howlike = {}
    #遍历所有文章的列表
    for onearticle in articlelist:
        #每篇文章的标签字典
        tagDictionary = {}
        #赋值标签字典
        tags = onearticle.tags.slugs()
        for tag in tags:
            tagDictionary[tag] = 1
        #计算当前的文章标签字典与平均值字典之间的向量距离
        distance2 = 0
        #遍历用户标签字典
        for key,value in taglike.items():
            #如果当前标签在内容标签中存在
            if key in tagDictionary:
                distance2 += (value-tagDictionary[key])**2
            else:
                distance2 += value**2
        #遍历内容标签字典
        for key,value in tagDictionary.items():
            if not key in taglike:
                distance2 += value**2
        distance = distance2**0.5
        #将文章id和距离添加到字典中
        howlike[onearticle.id] = distance
    #将得到的文章id与喜爱程度字典排序
    sortdict = dict(sorted(howlike.items(),key=lambda x: x[1]))
    articles = []
    for key,value in sortdict.items():
        article = ArticlePost.objects.get(id=key)
        articles.append(article)
    paginator = Paginator(articles, 3)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    context = {"articles":articles}
    return render(request, 'article/list.html', context)


#文章列表的视图函数(旧，不再使用)
'''
def article_list(request):
    # 根据GET请求中查询条件
    # 返回不同排序的对象数组
    if request.GET.get('order') == 'total_views':
        #获取所有文章按-total_views排序
        article_list = ArticlePost.objects.all().order_by('-total_views')
        #设置排序的名称
        order = 'totla_views'
    else:
        #默认排序
        article_list = ArticlePost.objects.all()
        order = 'normal'
    #每页显示2篇文章
    paginator = Paginator(article_list,3)
    #获取url中的页码  在url的末尾加上?key=value的键值对,request.GET.get('key')
    page = request.GET.get('page')
    #将页码对应的文章返回给articles
    articles = paginator.get_page(page)
    #需要传递给模板的对象，字典格式
    context = {'articles':articles,'order':order}
    #render函数：载入模板并返回context对象
    #参数，request    固定的request对象
    #     article/list.html  模板文件的路径
    #     coontext    传递到模板的数据
    return  render(request,'article/list.html',context)
'''

# 引入 Q 对象
from django.db.models import Q
#文章列表的视图函数(新,包含简单的搜索和排序功能)
def article_list(request):
    #获取GET请求中的search和order等查询参数数据
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')
    #初始化查询集
    article_list = ArticlePost.objects.all()
    '''
    #如果search存在
    if search:
        #如果排序方式为浏览量
        if order == 'total_views':
            # 用Q对象进行联合搜索
            #搜索标题或正文包含search的文章列表,并排序
            #icontains查询不区分大小写
            #contains查询区分大小写
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            ).order_by('-total_views')
        else:
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            )
    #search不存在,表示当前没有搜索操作search=null
    else:
        # 将search参数重置为空
        search = ''
        #判断是否排序
        if order == 'total_views':
            article_list = ArticlePost.objects.all().order_by('-total_views')
        else:
            article_list = ArticlePost.objects.all()
    '''
    #搜索查询集
    if search:
        article_list = article_list.filter(
            Q(title__icontains=search)|
            Q(body__icontains=search)
        )
    else:
        search=''

    #栏目查询集
    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)

    #标签查询集
    if tag and tag != 'None':
        #django-taggit中标签过滤的写法
        article_list = article_list.filter(tags__name__in = [tag])

    #查询集排序
    if order == 'total_views':
        article_list = article_list.order_by('-total_views')

    paginator = Paginator(article_list, 3)
    page = request.GET.get('page')
    articles = paginator.get_page(page)
    #将需要返回的数据赋值给context
    context = {
        'articles':articles,
        'order':order,
        'search':search,
        'column':column,
        'tag':tag,
    }
    return render(request, 'article/list.html', context)

#文章详情
def article_detail(request,id):
    #根据id取出相应的文章
    article = ArticlePost.objects.get(id = id)
    # 获取该文章的评论  filter可以查询多个对象而get只能查询一个对象
    comments = Comment.objects.filter(article=id)
    # 每次调用某文章详情页则浏览量字段+1并保存
    article.total_views += 1
    #update_fields=[]指定了数据库只更新total_views特定字段，优化执行效率
    article.save(update_fields=['total_views'])
    #点赞数
    likelist = likes.objects.filter(article=article)
    likenum = likelist.count()
    #当前用户是否点赞
    like = likes.objects.filter(Q(article=id) & Q(user=request.user.id))
    if like:
        islike = True
    else:
        islike = False

    #markdown.markdown语法接收两个参数：
    #第一个参数是需要渲染的文章正文article.body；
    #第二个参数载入了常用的语法扩展，markdown.extensions.extra中包括了缩写、表格等扩展，
    #markdown.extensions.codehilite则是后面要使用的代码高亮扩展。
    #代码块语法如下(语法错误会导致输出格式有问题):
    #```Python
    #代码内容
    #```
    #将markdown语法渲染成html样式
    #只能在文章中使用自动生成目录,不够实用
    '''
    article.body = markdown.markdown(article.body,
            extensions=[
                #包含缩写，表格等常用扩展
                'markdown.extensions.extra',
                #语法高亮扩展
                'markdown.extensions.codehilite',
                #目录扩展
                'markdown.extensions.toc',#在文章中的任意位置插入[TOC]字符串,自动生成目录
            ])
    '''
    #修改后可以在页面内使用目录
    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ]
    )
    #使用convert方法将正文渲染成html页面，通过md.toc将目录传递给模板
    article.body = md.convert(article.body)
    #引入评论表单
    comment_form = CommentForm()
    #需要传递给模板的对象，字典格式
    context = {'article':article,'toc':md.toc, 'comments': comments,'comment_form':comment_form,'likes':likenum,'islike':islike}
    #返回模板context对象
    return render(request,'article/detail.html',context)

#引入文章的form类
from .forms import ArticlePostForm, ArticleColumnForm
#引入User模型类
from django.contrib.auth.models import User

#新建栏目
@login_required(login_url='account_login')
def column_create(request):
    if request.method == "POST":
        article_column_form = ArticleColumnForm(request.POST)
        if article_column_form.is_valid():
            new_column = article_column_form.save(commit=False)
            new_column.author = User.objects.get(id=request.user.id)
            new_column.save()
            return redirect("article:article_create")
        else:
            return HttpResponse("表单内容有误请重新填写")
    else:
        article_column_form = ArticleColumnForm()
        context = {"article_column_form":article_column_form}
        return render(request,'article/create_column.html',context)

#写文章的视图
@login_required(login_url='account_login')
def article_create(request):
    #判断用户是否提交数据POST请求还是获取数据GET请求
    '''
    如果是POST提交数据，将post提交的表单赋值给article_post_form实例
    使用jdango内置方法 .is_valid()判断提交的数据是否符合模型的要求
    '''
    if request.method == "POST":
        #定义表单实例article_post_form并赋值data=request.POST,用户提交的数据
        article_post_form = ArticlePostForm(request.POST)
        #判断实例对象是否满足模型的要求
        if article_post_form.is_valid():
            #保存数据，暂时不提交到数据库commit=False
            new_article = article_post_form.save(commit=False)
            #指定id为1的User对象为作者
            #new_article.author = User.objects.get(id=1)
            #指定当前登录用户为作者
            new_article.author = User.objects.get(id=request.user.id)
            #如果文章的栏目数据存在
            if request.POST['column'] != 'none':
                #设置文章的栏目
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            #将新文章保存到数据库中
            new_article.save()
            #保存tags的多对多关系
            article_post_form.save_m2m()
            #完成后返回文章列表      重定向操作
            return redirect("article:article_list")
        #如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误请重新填写")
    #如果是POST请求数据，返回一个空的表单类对象，提供给用户填写
    else:
        #创建表单类实例

templates/article/create.html
{# 继承基本模板 #}
{% extends "base.html" %}
{# 引入静态文件 #}
{% load static %}
{# title的block #}
{% block title %} 写文章 {% endblock title %}
{# content的block #}
{% block content %}
{# 写文章的表单div #}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            {# 提交文章的表单 #}
            <form method="post" action="." enctype="multipart/form-data">
                {# Django中需要POST数据的地方都必须有csrf_token #}
                {% csrf_token %}
                {# 文章标题部分 #}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    {# 标题输入框 #}
                    <input type="text" class="form-control col-6" id="title" name="title" required>
                </div>
                {# 文章栏目 #}
                <div class="form-group">
                    <label for="column">栏目</label>
                    <select class="form-control col-6"
                            id="column"
                            name="column"
                    >
                            <option value="none">请选择栏目..</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}">{{ column }}</option>
                        {% endfor %}
                    </select>
                    <a href="{% url 'article:column_create' %}">新建栏目</a>
                </div>
                {# 文章标签 #}
                <div class="form-group">
                    <label for="tags">标签</label>
                    <input type="text"
                           class="form-control col-3"
                           id="tags"
                           name="tags"
                    >
                </div>
                {# 文章正文部分 #}
                <div class="form-group">
                    <label for="body">文章正文</label>
                    {# 正文输入框 #}
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                {# 按钮 #}
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/create_column.html
{% extends "base.html" %}
{% load static %}
{% block title %} 新建栏目 {% endblock title %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <lable for="title">栏目标题</lable>
        <input type="text" class="form-control" id="title" name="title">
        <button type="submit" class="btn btn-primary">完成</button>
    </form>
{% endblock content %}

templates/article/detail.html
{#模板继承#}
{% extends "base.html" %}
{% load static %}

{#title标题block#}
{% block title %}
文章详情
{% endblock %}

{#content block#}
{% block content %}
<script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'prism/prism.css' %}">
    <div class="container">
        <div class="row">
            {# 从对象获取标题和作者 #}
            <div class="col-9">
                <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
                {# 文章信息 #}
                <div class="col-12 alert alert-primary">
                    <div>
                        作者：<a href="{% url 'userprofile:personal' article.author.id %}">{{ article.author }}</a>
                        {% if user == article.author %}
                            {# 为防止用户误操作,不设置点击直接调用删除视图函数 #}
                            {# 设置onclick属性,调用下面的确认函数,点击确认后才调用视图函数 #}
                            · <a href="#" onclick="confirm_safe_delete()">删除文章</a>
                            · <a href="{% url "article:article_update" article.id %}">编辑文章</a>
                        {% endif %}
                    </div>
                    <div>
                        浏览：{{ article.total_views }} &nbsp;&nbsp;
                    </div>
                    {# 一个隐藏的表单 #}
                    <form
                            style="display: none;"
                            id="safe_delete"
                            action="{% url 'article:article_safe_delete' article.id %}"
                            method="post"
                    >
                    {% csrf_token %}
                        <button type="submit">发送</button>
                    </form>
                </div>
                {# 文章正文 #}
                <div class="col-12">
                    {# django会自动将输出的html进行转义 过滤器safe表示这里不需要转义 #}
                    <p>{{ article.body|safe }}</p>
                </div>
                {% if islike %}
                    <button onclick="likes()"  class="btn btn-light">
                        <i class="fa fa-thumbs-up" aria-hidden="true"></i>&nbsp;已点赞&nbsp;{{ likes }}
                    </button>
                {% else %}
                    <button onclick="likes()"  class="btn btn-light">
                        <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>&nbsp;点赞&nbsp;{{ likes }}
                    </button>
                {% endif %}
                {# 一个隐藏的表单 #}
                <form
                        style="display: none;"
                        id="clicklike"
                        action="{% url 'article:clicklike' article.id %}"
                        method="post"
                >
                {% csrf_token %}
                    <button type="submit">发送</button>
                </form>
                {# 发表评论 #}
                {% if user.is_authenticated %}
                    <div>
                        <form action="{% url 'comment:post_comment' article.id %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="body">
                                    <strong>
                                        我也要发言:
                                    </strong>
                                </label>
                                    {#<textarea type="text" class="form-control" id="body" name="body" rows="2"></textarea>#}
                                    <div>
                                        {{ comment_form.media }}
                                        {{ comment_form.body }}
                                    </div>
                            </div>
                            <button type="submit" class="btn btn-primary">发送</button>
                        </form>
                    </div>
                {% else %}
                    <br>
                    <h5 class="row justify-content-center">
                    请<a href="{% url 'userprofile:login' %}">登录</a>后评论
                    </h5>
                    <br>
                {% endif %}
                {# 已有评论的显示部分 #}
                {% load mptt_tags %}
                <h4>共有{{ comments.count }}条评论</h4>
                <div class="row">
                    {# 遍历树形结构的评论 #}
                    {% recursetree comments %}
                        {# 给节点node重命名为comment #}
                        {% with comment=node %}
                            {# 判断此评论的reply_to是评论还是文章 赋值不同的class用于使用不同的样式 #}
                            <div class="{% if comment.reply_to %}
                                        offset-1 col-11
                                        {% else %}
                                        col-12
                                        {% endif %}"  id="comment_elem_{{ comment.id }}"
                            >
                                <hr>
                                <p>
                                    <strong style="color: pink">
                                        {{ comment.user }}
                                    </strong>
                                    {# 如果评论的目标是评论 显示被回复的用户 #}
                                    {% if comment.reply_to %}
                                        <i class="fa fa-caret-right"
                                           style="color: cornflowerblue;"
                                        ></i>
                                        <strong style="color: pink">
                                            {{ comment.reply_to }}
                                        </strong>
                                    {% endif %}

                                </p>
                                <div>{{ comment.body|safe }}</div>

                                <div>
                                    <span style="color: gray">
                                        {{ comment.created|date:"Y-m-d H:i" }}
                                    </span>

                                    {# 加载 modal 的按钮 #}
                                    {# 判断用户是否登录 #}
                                    {% if user.is_authenticated %}
                                    {# 点击调用load_modal方法传递文章和评论id参数 #}
                                    <button type="button"
                                            class="btn btn-light btn-sm text-muted"
                                            onclick="load_modal({{ article.id }}, {{ comment.id }})"
                                            >
                                        回复
                                    </button>
                                    {% else %}
                                    <a class="btn btn-light btn-sm text-muted"
                                       href="{% url 'userprofile:login' %}"
                                       >
                                        回复
                                    </a>
                                    {% endif %}
                                </div>

                                <!-- Modal -->
                                <div class="modal fade"
                                     id="comment_{{ comment.id }}"
                                     tabindex="-1"
                                     role="dialog"
                                     aria-labelledby="CommentModalCenter"
                                     aria-hidden="true"
                                >
                                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                        <div class="modal-content" style="height: 480px">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}：</h5>
                                            </div>
                                            <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                        </div>

                                    </div>
                                </div>

                                {% if not comment.is_leaf_node %}
                                    <div class="children">
                                        {{ children }}
                                    </div>
                                {% endif %}
                            </div>


                        {% endwith %}
                    {% endrecursetree %}
                </div>
            </div>
            <!-- 目录 -->
            <div class="col-3 mt-4" id="sidebar" class="sidebar">
                <h4><strong>目录</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>
    </div>
    <script>
        function likes() {
            $('form#clicklike button').click();
        }
        function confirm_safe_delete(){
            layer.open({
                title:"确认删除",
                content:"确认删除这篇文章吗?",
                //点击确认后
                yes: function(index,layero){
                    //自动点击隐藏表单中的发送按钮
                    //表单发起POST请求,并携带csrf令牌,避免csrf攻击
                    $('form#safe_delete button').click();
                    layer.close(index);
                }
            })
        }
        function delete_comment(comid){
            var formbtnid = 'form#delete_comment'+comid+' button';
            layer.open({
                title:"确认删除",
                content:"确认删除此评论吗?",
                //点击确认后
                yes: function(index,layero){
                    //自动点击隐藏表单中的发送按钮
                    //表单发起POST请求,并携带csrf令牌,避免csrf攻击
                    $(formbtnid).click();
                    layer.close(index);
                }
            })
        }
    </script>
    <style>
        .sidebar{
            will-change: min-height;
        }

        .sidebar__inner{
            transform: translate(0, 0);
            transform: translate3d(0, 0, 0);
            will-change: position, transform;
        }
    </style>
{% endblock %}

{% block script %}
<script>
    $(".django-ckeditor-widget").removeAttr('style');
</script>
<!-- 引入粘性侧边栏 -->
<script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
<script type="text/javascript">
    $('#sidebar').stickySidebar({
        topSpacing: 20,
        bottomSpacing: 20,
    });
</script>
<script>
    // 加载 modal
    function load_modal(article_id, comment_id) {
        let modal_body = '#modal_body_' + comment_id;
        let modal_id = '#comment_' + comment_id;

        // 加载编辑器
        if ($(modal_body).children().length === 0) {
            let content = '<iframe src="/comment/post_comment/' +
                article_id +
                '/' +
                comment_id +
                '"' +
                ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' +
                comment_id +
                '"></iframe>';
            //找到对应Modal的容器，并将一个iframe容器动态添加进去
            $(modal_body).append(content);
        };
        //找到对应的Modal，并将其唤醒
        $(modal_id).modal('show');
    }

    // 新增函数，处理二级回复
    function post_reply_and_show_it(new_comment_id) {
        let next_url = "{% url 'article:article_detail' article.id %}";
        // 去除 url 尾部 '/' 符号
        next_url = next_url.charAt(next_url.length - 1) == '/' ? next_url.slice(0, -1) : next_url;
        // 刷新并定位到锚点
        window.location.replace(next_url + "#comment_elem_" + new_comment_id);
    };
</script>
{% endblock script %}